# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99544df57a78301f2dcc4a96d1e56ce2111f022c10a80e36f5e97aaf6f6f4ab77cb1ab7fc9e8972689827038f780816dcb8ce05bf9c3d077da5ef7f7add57bcd

test:
  secret_key_base: 2106ecd205e0127523d6695a37dd4a734d1405e6e42e127a9a7784aa6d39f67019697a6c117091a24e3e98f6f5c546a4f6f814dc74ef787ea2b9b4b25487e05f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
